# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80db7f7aa7d26cd800009a8b5170516136fc9a80cf4a5628cc0441a6129b94b5388b04be4cdda4489b9fed189b1320beec7fc17a73536d3e315e8851e7d4639a

test:
  secret_key_base: c23e74689136d401de5bb6770b7ebb1a50d870ed8df8e5c3f7147dcbd8d06e8f85568e5b503282c9ee952f6ba6970e90b8cc1323af98bc3e61e9f4f86b4894aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
